# Dockerfile

# 1. ベースとなる公式Pythonイメージを指定
FROM python:3.10-slim

# 3. 依存ライブラリを先にインストール
#    (ソースコードより先にコピーすることで、ビルドキャッシュが効きやすくなる)
COPY ./requirements.txt ./requirements.txt
COPY ./requirements-dev.txt ./requirements-dev.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt

# 3. アプリケーションのソースコードをコンテナにコピー
COPY . /app

WORKDIR /app/src

# 実行権限を付与
RUN chmod +x /app/entrypoint.sh
# コンテナ起動時にこのスクリプトを実行するように設定
ENTRYPOINT ["/app/entrypoint.sh"]

# 6. コンテナ起動時にこのコマンドを実行する
#    Uvicornサーバーを起動し、外部からのアクセスを許可する
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]