"""scheduleテーブルの内容を変更

Revision ID: 04103131b154
Revises: 3d340efbe209
Create Date: 2025-09-20 03:30:56.156038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04103131b154'
down_revision: Union[str, Sequence[str], None] = '3d340efbe209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eco_action_achievements', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('eco_action_achievements', 'eco_action_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('schedules', 'all_day',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('schedules', 'start_schedule',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('schedules', 'end_schedule',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'end_schedule',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('schedules', 'start_schedule',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('schedules', 'all_day',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('eco_action_achievements', 'eco_action_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('eco_action_achievements', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
