"""エコ活テーブルの作成

Revision ID: 139e9b2f6dbf
Revises: b79dc12df5c9
Create Date: 2025-09-13 16:25:04.339507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139e9b2f6dbf'
down_revision: Union[str, Sequence[str], None] = 'b79dc12df5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eco_actions',
    sa.Column('eco_action_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('money_saved', sa.Float(), nullable=True),
    sa.Column('co2_reduction', sa.Float(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('eco_action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eco_actions')
    # ### end Alembic commands ###
