"""全体統計テーブルの追加

Revision ID: 3d340efbe209
Revises: aeb40dd83466
Create Date: 2025-09-19 18:05:37.816966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d340efbe209'
down_revision: Union[str, Sequence[str], None] = 'aeb40dd83466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overall_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_money_saved', sa.Float(), nullable=True),
    sa.Column('total_co2_reduction', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('eco_action_achievements', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eco_action_achievements', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('overall_stats')
    # ### end Alembic commands ###
