"""ユーザー統計テーブルの追加

Revision ID: 4a701dda4d61
Revises: 04103131b154
Create Date: 2025-10-04 06:17:22.477315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a701dda4d61'
down_revision: Union[str, Sequence[str], None] = '04103131b154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_money_saved', sa.Float(), nullable=True),
    sa.Column('total_co2_reduction', sa.Float(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_statistics')
    # ### end Alembic commands ###
