"""ユーザー統計テーブルの追加

Revision ID: 5fa0a0aee1fd
Revises: 04103131b154
Create Date: 2025-10-04 07:40:46.097352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa0a0aee1fd'
down_revision: Union[str, Sequence[str], None] = '04103131b154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_money_saved', sa.Float(), nullable=True),
    sa.Column('total_co2_reduction', sa.Float(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_statistics')
    # ### end Alembic commands ###
