"""エコ活達成状況テーブルの追加

Revision ID: aeb40dd83466
Revises: 139e9b2f6dbf
Create Date: 2025-09-18 07:10:13.549937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb40dd83466'
down_revision: Union[str, Sequence[str], None] = '139e9b2f6dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eco_action_achievements',
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('eco_action_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['eco_action_id'], ['eco_actions.eco_action_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.schedule_id'], ),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eco_action_achievements')
    # ### end Alembic commands ###
