"""schedulesテーブルを作成

Revision ID: d924423b8648
Revises: 7eb0020caf0b
Create Date: 2025-09-08 09:27:29.461326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd924423b8648'
down_revision: Union[str, Sequence[str], None] = '7eb0020caf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=True),
    sa.Column('start_schedule', sa.DateTime(), nullable=True),
    sa.Column('end_schedule', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('all_day IS NOT NULL OR (start_schedule IS NOT NULL AND end_schedule IS NOT NULL)', name='ck_schedule_time_constraint'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    # ### end Alembic commands ###
