"""googleアカウントの認証情報をcredentialsテーブルのカラムに追加

Revision ID: ed21ba122a83
Revises: b0c8b0dc33b2
Create Date: 2025-09-01 09:30:22.281450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed21ba122a83'
down_revision: Union[str, Sequence[str], None] = 'b0c8b0dc33b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('user_credentials', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'user_credentials', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_credentials', type_='unique')
    op.alter_column('user_credentials', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_credentials', 'google_id')
    # ### end Alembic commands ###
