"""カテゴリーテーブル作成とスケジュールテーブルの関連付けを定義

Revision ID: fb5a5493d1c5
Revises: d924423b8648
Create Date: 2025-09-12 04:31:35.577270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5a5493d1c5'
down_revision: Union[str, Sequence[str], None] = 'd924423b8648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.add_column('schedules', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'schedules', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
